cyder/core/cyuser/backends.py, cyder/core/cyuser/tests/test_perms.py
=> Verify and fix permissions

cyder/cydhcp/range/models.py, cyder/cydhcp/range/utils.py
=> Improve Range stringification

cyder/templates/base/base.html, media/css/base.scss, media/css/base_mobile.scss, media/js/views.js
**Resolves issues #803 and #807.**
=> A few HTML, CSS, and JS bugfixes

cyder/settings/base.py, cyder/templates/base/list.html
This should be removed until https://github.com/OSU-Net/cyder/pull/562 is ready. Which will be after feature freeze.
=> Remove editable grid

cyder/cydns/soa/models.py
=> Fix SOA.filter_by_ctnr

cyder/initial_data/05_workgroup.json, cyder/management/commands/dhcp_migrate.py
I forgot to add this initial data file, which was causing tests to fail.
=> Fix default workgroup again

cyder/settings/local.py-dist, cyder/templates/base/base.html, media/css/base.scss, media/js/views.js
=> Fix Django Debug Toolbar

media/css/base.scss
As mentioned in a user bug report.
=> Fix issue where sidebar remains hidden after expanding out of mobile view

media/js/application.js, media/js/systemform.js
Resolves: https://github.com/OSU-Net/cyder/issues/846
=> Form submit keypress logic

media/css/lib/jquery.tagsinput.css
Only used in clone user perms form
=> Update tags input color to match the current theming

cyder/base/fields.py, cyder/cydhcp/validation.py
=> Raise ValidationError if MacAddrField value is too long

cyder/management/commands/lib/maintain_dump.py
I don't think we'd have any issues, but I just wanted to make sure.
=> Properly quote MySQL passwords

media/js/views.js
=> Fix issue with loading gif displaying forever on empty list view object creation

cyder/cydns/domain/models.py
=> Fix Domain.create_recursive so it's actually atomic

cyder/base/models.py, cyder/base/tablefier.py, cyder/core/cyuser/backends.py, cyder/core/system/models.py, cyder/cydhcp/interface/dynamic_intr/models.py, cyder/cydns/models.py, cyder/cydns/nameserver/models.py, cyder/templates/system/system_detail.html
Should resolve https://github.com/OSU-Net/cyder/issues/874
Also allows users to edit objects outside of the active container, as long as they have permission to the object itself.
=> Fix search ctnr perms

cyder/templates/cydns/cydns_view.html
Fix issue where form was not created with getform so meta data was not added
Resolves https://github.com/OSU-Net/cyder/issues/915
=> 915 - Fix issue with ptrs and addressrecord were returning dynamic ranges

cyder/templates/search/search.html
JS quirks. Meh.
Resolves https://github.com/OSU-Net/cyder/issues/907
=> Fix issue with initforms storing the submit button on search page

cyder/core/system/views.py
Remove ctnr field from dynamic/static interface form in combined system form
Resolves https://github.com/OSU-Net/cyder/issues/905
=> Combined system form double ctnr field in global

cyder/cydns/domain/models.py, cyder/cydns/domain/tests/basic_tests.py, cyder/cydns/models.py
=> Disallow domain renaming

cyder/core/ctnr/urls.py, cyder/core/ctnr/views.py, cyder/settings/base.py, cyder/templates/ctnr/ctnr_detail.html, media/js/buttonLogic.js, media/js/constants.js, media/js/ctnr/ctnr.js, media/js/utils.js, media/js/views.js
Resolves https://github.com/OSU-Net/cyder/issues/933
=> Refactor add object to ctnr form

cyder/templates/base/detail.html, cyder/templates/base/list.html, cyder/templates/core/core_list.html, cyder/templates/core/core_view.html, cyder/templates/cydhcp/cydhcp_view.html, cyder/templates/cydns/cydns_view.html, cyder/templates/search/search.html, media/js/systemform.js
Resolves https://github.com/OSU-Net/cyder/issues/921
=> Don't load form on empty list view

cyder/api/authtoken/models.py
Resolves https://github.com/OSU-Net/cyder/issues/929
@drkitty, did I implement these properties correctly? I just copied what I saw in the VLAN and VRF models.
=> Add pretty_name and pretty_type fields to API tokens

cyder/base/tablefier.py, cyder/base/utils.py, cyder/base/views.py, cyder/cydhcp/range/views.py, cyder/cydhcp/workgroup/views.py, cyder/cydns/domain/views.py, cyder/templates/range/range_detail.html
Resolves https://github.com/OSU-Net/cyder/issues/936
=> Show Obj's ctnr in detail view

cyder/api/authtoken/models.py, cyder/core/cyuser/backends.py
Fixes https://github.com/OSU-Net/cyder/issues/948
=> Add get_ctnrs method to api token objects

cyder/templates/base/base.html
=> Fix issue with header level to ctnr underlining on hover

cyder/core/ctnr/forms.py
Fixes: https://github.com/OSU-Net/cyder/issues/942
=> Remove m2m fields from ctnr edit form

cyder/base/views.py
Resolves https://github.com/OSU-Net/cyder/issues/898
=> Use utf-8 encoding rather than str to sort intrs

cyder/cydns/views.py
Solves https://github.com/OSU-Net/cyder/issues/896
=> Show dns statistics in global

cyder/cydns/nameserver/forms.py, cyder/cydns/nameserver/models.py, cyder/cydns/tests/test_views.py
Resolves https://github.com/OSU-Net/cyder/issues/943
=> Allow the server and domain name to be the same for nameserver records

cyder/cydns/soa/forms.py
Fixes https://github.com/OSU-Net/cyder/issues/946
=> Replace @ with . in soa form clean

cyder/base/mixins.py, cyder/base/views.py, cyder/core/system/views.py, cyder/cydhcp/interface/dynamic_intr/forms.py, cyder/cydhcp/interface/static_intr/forms.py
Fixes: https://github.com/OSU-Net/cyder/issues/924
Also might fix https://github.com/OSU-Net/cyder/issues/877
=> Show all ctnr fields

cyder/base/tablefier.py, cyder/core/ctnr/views.py, cyder/core/system/models.py, cyder/core/system/views.py, cyder/templates/base/tables.html, cyder/templates/ctnr/ctnr_detail.html, cyder/templates/system/system_detail.html, media/css/tables.scss
Fixes: https://github.com/OSU-Net/cyder/issues/880
=> Detail page styling

cyder/cydhcp/range/models.py, cyder/fixtures/dhcp_build_test.json, cyder/fixtures/dns_build_test.json, cyder/management/commands/dhcp_migrate.py
**Resolves issue #945.**
*Requires a schema migration.*
=> Remove VoIP special stuff

cyder/base/vcs.py, cyder/cydhcp/build/builder.py, cyder/cydhcp/build/tests/build_tests.py, cyder/cydns/cybind/builder.py, cyder/cydns/cybind/tests/build_tests.py, cyder/settings/base.py
=> Simple config change threshold

cyder/core/utils.py, cyder/cydns/cybind/zone_builder.py, cyder/settings/local.py-dist, cyder/settings/local.py-travis
=> Fix fail_mail

cyder/cydhcp/tests/test_views.py
Somehow `RangeViewTests` started failing on master. This pull request fixes it.
=> Fix Range view test

cyder/api/v1/tests/base.py, cyder/base/eav/fields.py, cyder/base/eav/forms.py, cyder/base/eav/models.py, cyder/cydhcp/network/models.py, cyder/cydhcp/workgroup/models.py, cyder/templates/base/utility.html, media/js/views.js
=> Remove EAV autocomplete

cyder/api/v1/endpoints/dhcp/static_interface/tests.py, cyder/cydhcp/interface/static_intr/models.py, cyder/cydhcp/interface/static_intr/tests/basic_tests.py, cyder/cydhcp/interface/static_intr/tests/deletion_tests.py, cyder/cydhcp/range/models.py, cyder/cydhcp/range/tests/ipv4_tests.py, cyder/cydns/address_record/tests/test_models.py, cyder/cydns/cname/tests/test_models.py, cyder/cydns/domain/tests/test_auto_delete.py
Resolves https://github.com/OSU-Net/cyder/issues/982
=> Validate container permissions for static interface-range relationships

cyder/search/compiler/dsl.py
=> Use ROOT in search query grammar file path

cyder/core/system/models.py
=> Fix system clean so that it uses proper validation for dynamic interfaces

cyder/core/system/forms.py
Resolves https://github.com/OSU-Net/cyder/issues/989
=> Sort containers in the basic System form

cyder/cydns/search_utils.py
**Resolves issue #802.**
The real question is: Why is this code path never used, and can we remove it?
=> Fix _build_queries

cyder/base/utils.py
Resolves https://github.com/OSU-Net/cyder/issues/1003
=> Filter feature doesn't return duplicate items

cyder/cydhcp/site/models.py
Also, show all sites in list view.
Resolves https://github.com/OSU-Net/cyder/issues/1006.
=> Sites can no longer be descended from themselves.

cyder/base/utils.py, cyder/core/utils.py, cyder/cydhcp/build/builder.py, cyder/cydhcp/build/tests/build_tests.py, cyder/cydns/cybind/builder.py, cyder/cydns/cybind/tests/build_tests.py
=> Send email and create a stop file on build failure

cyder/search/compiler/invfilter.py, cyder/search/views.py
=> Make global search look at network and range searchable fields

cyder/base/views.py, cyder/cydhcp/interface/dynamic_intr/models.py, cyder/cydhcp/interface/static_intr/models.py
EDIT: Also removes it from detail views.
=> Remove last seen columns from interface list views

cyder/base/tablefier.py, cyder/core/ctnr/views.py
resolves https://github.com/OSU-Net/cyder/issues/1021
=> Remove object update and delete icons from the container detail view

cyder/core/ctnr/models.py
Resolves https://github.com/OSU-Net/cyder/issues/1031
=> Fix removing ranges from containers

cyder/cydhcp/interface/dynamic_intr/models.py, cyder/cydhcp/interface/static_intr/models.py
Resolves https://github.com/OSU-Net/cyder/issues/1009
=> Check workgroup when saving an interface

cyder/cydhcp/interface/static_intr/models.py, cyder/cydhcp/interface/static_intr/tests/A_tests.py, cyder/cydns/address_record/models.py, cyder/fixtures/dns_build_test.json, cyder/migrations/0009_auto__del_unique_addressrecord_label_domain_fqdn_ip_upper_ip_lower_ip_.py
Fixes mistakes in https://github.com/OSU-Net/cyder/pull/1027.
```irc
12:54 <@murrown> ARs: unique by (fqdn, ip_str)
12:55 <@murrown> SIs: unique by fqdn and ip_str
12:55 <@murrown> SIs w/ ARs: unique by fqdn, but can share IPs
```
=> Really truly fix static interface and address record conflict validation

cyder/base/tablefier.py
Resolves https://github.com/OSU-Net/cyder/issues/1034
=> Retrieve user profiles without destroying the ordering

cyder/base/tablefier.py
Solution for https://github.com/OSU-Net/cyder/issues/1048
=> Remove delete buttons from all Ctnr tables

cyder/search/compiler/invfilter.py, cyder/search/views.py
Resolves https://github.com/OSU-Net/cyder/issues/1040
=> Add workgroups to Cyder search

cyder/core/ctnr/models.py, cyder/cydhcp/interface/static_intr/models.py, cyder/cydhcp/network/models.py, cyder/cydhcp/range/models.py, cyder/cydhcp/supernet/models.py, cyder/cydns/address_record/models.py, cyder/cydns/cname/models.py, cyder/cydns/mx/models.py, cyder/cydns/nameserver/models.py, cyder/cydns/ptr/models.py, cyder/cydns/srv/models.py, cyder/cydns/sshfp/models.py, cyder/cydns/txt/models.py
Note that most of the added fields don't appear in the object's list view, so when they show up in the global search, it won't be clear why.
=> Add a bunch of text fields to search

cyder/cydhcp/urls.py, cyder/search/urls.py
Resolves https://github.com/OSU-Net/cyder/issues/1045
=> Add cyder revision to extra context of direct_to_template urls

cyder/base/tablefier.py, cyder/base/utils.py, cyder/base/views.py, cyder/cydhcp/range/views.py, cyder/settings/base.py, media/js/constants.js
The other half of https://github.com/OSU-Net/cyder/issues/1048
=> Add remove container button to all lists of containers in detail views

cyder/cydhcp/network/forms.py
Solution for https://github.com/OSU-Net/cyder/issues/1015
=> Autocreate routers option

cyder/cydhcp/network/forms.py
fix bug in network creation form where the auto-generated routers option is incorrect.
=> add 1 to network to make proper gateway

cyder/api/v1/endpoints/dns/soa/api.py, cyder/cydhcp/network/models.py, cyder/cydhcp/range/models.py, cyder/cydhcp/workgroup/models.py
make it harder to delete workgroups... fix a dhcp build bug
=> fix some stuff
