OSU-Net/cyder

cyder/management/commands/lib/fix_maintain.py

This will cause `fix_maintain` to work as it originally did, and migrate TLDs.

Unwrap the 1-tuple in fix_maintain

---

cyder/cydhcp/network/models.py
cyder/cydhcp/network/tests.py

**Resolves issue #760.**
This is mostly for debugging, but eventually we might want to show a network's children on network detail pages.

Implement and test `Network.children`

---

cyder/base/mixins.py
cyder/base/utils.py
cyder/base/vcs.py
cyder/cydhcp/build/builder.py
cyder/cydhcp/build/tests/build_tests.py
cyder/cydhcp/range/models.py
cyder/cydns/cybind/builder.py
cyder/cydns/cybind/tests/build_tests.py
cyder/management/commands/bindbuild.py
cyder/management/commands/dhcp_build.py

Simplify (?) config builder logging

---

cyder/cydhcp/constants.py
cyder/cydhcp/interface/dynamic_intr/models.py
cyder/cydhcp/interface/static_intr/models.py
cyder/cydhcp/workgroup/models.py
cyder/fixtures/dhcp_build_test.json
cyder/fixtures/dns_build_test.json
cyder/management/commands/dns_migrate.py

This pull request adds the default workgroup to every interface's dropdown, and makes the workgroup field non-nullable. It does NOT force containers for workgroups and interfaces to match. Partially resolves https://github.com/OSU-Net/cyder/issues/841

Fix default workgroup

---

cyder/base/tablefier.py
cyder/base/views.py
cyder/core/system/views.py
cyder/cydhcp/build/builder.py
cyder/cydhcp/network/views.py
cyder/cydhcp/range/views.py
cyder/cydhcp/vrf/views.py
cyder/cydns/cybind/builder.py
cyder/cydns/cybind/serial_utils.py
cyder/templates/base/detail.html
cyder/templates/base/tables.html
cyder/templates/range/range_detail.html
cyder/templates/search/search_help.html
cyder/templates/system/system_detail.html
media/css/base.scss
media/css/tables.scss
media/js/admin.js
media/js/views.js

**Resolves issues #446, #704, #332, #828, #831 and #768*.**
*Changed how main object is rendered in detail view to make it not look like a table.  'Info' row is also removed as it doesn't do anything useful. 
\* Examples of using '!' to negate a query still need to be added.

In detail views, show main object info in a vertical list instead of a one-row table

---

cyder/cydhcp/range/utils.py
media/js/constants.js
media/js/rangewizard.js
media/js/systemform.js

Resolves https://github.com/OSU-Net/cyder/issues/848.
Previously the system form was not changing its interface type metadata when interface type was changed. 
I also added a getMsg function to constants for easy ui message handling. I plan on slowly migrating all text used in js to this function.

System form range bug

---

cyder/templates/base/sidebar.html

Resolves: https://github.com/OSU-Net/cyder/issues/889

Display workgroup menu item as singular rather than plural

---

media/js/views.js

**Resolves issue #908.**
A side-effect is that even opening a creation form scrolls to the top, but that doesn't really matter.

Scroll to top of page when opening an object form

---

cyder/core/cyuser/urls.py

**Resolves issue #882.**
Couldn't resist. It just looks dumb without the slash.

Require slash in 'become user' URL

---

cyder/cydhcp/interface/dynamic_intr/models.py

If no range was selected, `DynamicInterface.clean` would still try to access `self.range`, which would raise a `Range.DoesNotExist` exception (causing a server error).

FIx dynamic interface MAC address validation

---

cyder/cydhcp/vrf/models.py
cyder/cydhcp/vrf/tests.py
cyder/cydhcp/vrf/validators.py

Restrict VRF names to letters, numbers, hyphens, and underscores

---

cyder/cydhcp/interface/dynamic_intr/models.py

**Resolves issues #543, #672, and #806. Supersedes PR #635.**
This pull request changes how we build host declarations for dynamic interfaces. Using the interface's system's name as the first label of the hostname is bad, so I changed it so the first label contains the MAC address and the range's primary key.

Change dynamic interface hostnames

---

media/css/tables.scss

All other icons in tables slightly move when hovering. The update icon was underlining rather than moving.

Fix issue with update icon behaviour in tables

---

cyder/cydns/cybind/zone_builder.py

It seems like SOA records have two different ways of being built... the usual `bind_render_record`, and `zone_builder.render_soa_only`. This adds the TTL to the latter.
Resolves https://github.com/OSU-Net/cyder/issues/930

Add ttl to SOA records in builds

---

cyder/base/helpers.py
cyder/cydhcp/interface/dynamic_intr/models.py
cyder/cydhcp/interface/static_intr/models.py
cyder/cydhcp/network/models.py
cyder/cydhcp/range/models.py
cyder/cydns/address_record/models.py
cyder/cydns/ptr/models.py

This doesn't work for IPv6, dunno if that's really feasible without reworking how the tables sort so that they can sort on both `ip_upper` and `ip_lower`. So for IPv6 addresses, only the lower 64 bits will considered when sorting by IP address.

Sort interfaces, ARs, and PTRs by numeric IP, not ip_str

---

cyder/management/commands/lib/dhcpd_compare2/compare.py
cyder/search/compiler/Makefile
cyder/search/compiler/django_compile.py
cyder/search/compiler/dsl.py
cyder/search/compiler/invfilter.py
cyder/search/compiler/search.parsley
cyder/search/tests/test_parser.py
cyder/search/views.py
cyder/templates/search/search_help.html

**Resolves issue #958.**
Searching for a MAC address is now case-insensitive regardless of whether it's delimited by colons or hyphens or undelimited.

MAC address search fix

---

cyder/search/compiler/django_compile.py

**Resolves the issue seen recently in which searching for a square root symbol ("√") causes a server error.**
The problem was that either OMeta or Parsley doesn't correctly format parsing exception messages, and trying to stringify them causes a UnicodeDecodeError. This pull request works around the bug by changing the way we stringify parsing exceptions so that it can never raise a UnicodeDecodeError.

Unicode search fix

---

cyder/management/commands/lib/dhcpd_compare2/dhcp_objects.py

**Resolves issue #988.**
This one's pretty trivial. The diff used to look like this:
```none
subnet 10.0.0.0 netmask 255.0.0.0 {
pool {
+option routers 10.2.0.1;
}
}
subnet 192.168.0.0 netmask 255.255.0.0 {
-pool {
-    range 192.168.2.2 192.168.5.254;
-}
}
```
Now it looks like this:
```none
subnet 10.0.0.0 netmask 255.0.0.0 {
pool { # 10.2.0.2 - 10.2.255.254
+option routers 10.2.0.1;
}
}
subnet 192.168.0.0 netmask 255.255.0.0 {
-pool { # 192.168.2.2 - 192.168.5.254
-    range 192.168.2.2 192.168.5.254;
-}
}
```
It's redundant for pools that are added or removed, because you can see the `range` parameter itself, but it still might help if a pool has more than a few lines.

Add range comment to pool decls in dhcpd_compare2 output

---

cyder/base/constants.py
cyder/core/ctnr/models.py
cyder/core/ctnr/views.py
cyder/cydns/address_record/models.py

This is intended to prevent situations where, given an object with a matching container field and domain/range/workgroup field, if the domain/range/workgroup is removed from the container, a validation error will be raised so that an invalid object will not be left behind.
Resolves https://github.com/OSU-Net/cyder/issues/987

Check objects before removing them from containers

---

cyder/base/mixins.py
cyder/base/views.py
cyder/cydhcp/range/forms.py

This pull request does two things.
1. Objects are no longer automatically added to the current container when they are created.
2. The network list on the range create form shows all networks instead of only those associated with the current container.
Note that the 1st change is general and the 2nd change is specific. For 1, I could have instead only prevented Ranges from being automatically added. For 2, I could shown the full list in all forms for any object that doesn't have an explicit `ctnr` or `ctnr_set` field. But I chose this approach because it seemed the safest and most reasonable. If necessary, I can change it to the other approach.

Don't auto add objects to containers

---

cyder/base/mixins.py

This applies to all objects, not just systems.

Hide container field when creating a new object outside of global

---

cyder/cydhcp/interface/static_intr/models.py
cyder/cydhcp/interface/static_intr/tests/A_tests.py
cyder/cydns/address_record/models.py
cyder/cydns/address_record/tests/test_models.py
cyder/cydns/nameserver/tests/test_models.py

Resolves https://github.com/OSU-Net/cyder/issues/1026
Previously we allowed static interfaces and address records to share a name if they also shared a container, and did not share an IP address, but this specification has changed.

Make static interfaces and address records conflict properly
